# Generated by Django 5.0.1 on 2024-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateField()),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email_id", models.EmailField(max_length=254)),
                ("mobile_no", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("hash_key", models.CharField(max_length=255)),
                ("profile", models.ImageField(upload_to="profile_images/")),
                (
                    "agreement",
                    models.CharField(
                        choices=[("agree", "Agree"), ("disagree", "Disagree")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deactive", "Deactive")],
                        max_length=10,
                    ),
                ),
                ("last_change", models.DateTimeField()),
            ],
        ),
    ]
