# Generated by Django 5.0.1 on 2024-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email_id",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="mobile_no",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
