# Generated by Django 5.0.1 on 2024-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_users_email_id_alter_users_mobile_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email_id",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
