# Generated by Django 5.0.1 on 2024-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_alter_users_email_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email_id",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
