# Generated by Django 5.0.1 on 2024-01-09 02:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_users_hash_key_alter_users_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="old_file_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
