# Generated by Django 5.0.1 on 2024-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_shared_datahouse_datahouse_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahouse",
            name="file_password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shared_datahouse",
            name="file_password",
            field=models.CharField(max_length=100),
        ),
    ]
