# Generated by Django 5.0.1 on 2024-01-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_datahouse_file_secure_shared_datahouse_file_secure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting", name="current_storage", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="setting", name="storage", field=models.FloatField(),
        ),
    ]
