# Generated by Django 5.0.1 on 2024-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_datahouse_file_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shared_datahouse",
            name="file_secure",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                ],
                max_length=10,
            ),
        ),
    ]
