# Generated by Django 5.0.1 on 2024-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_shared_datahouse_file_secure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datahouse",
            name="file_secure",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                ],
                max_length=10,
            ),
        ),
    ]
