# Generated by Django 5.0.1 on 2024-01-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_users_old_file_name"),
        ("user", "0009_alter_setting_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shared_datahouse",
            name="to_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="login.users"
            ),
        ),
    ]
