# Generated by Django 5.0.1 on 2024-01-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_folder_shared_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="folder_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
