# Generated by Django 5.0.1 on 2024-01-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_folder_folder_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folder", old_name="file_status", new_name="folder_status",
        ),
        migrations.RenameField(
            model_name="shared_folder",
            old_name="file_status",
            new_name="folder_status",
        ),
        migrations.AddField(
            model_name="shared_folder",
            name="folder_files",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shared_folder",
            name="folder_size",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
