# Generated by Django 5.0.1 on 2024-01-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_rename_file_status_folder_folder_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shared_folder",
            old_name="folder_status",
            new_name="folder_statu",
        ),
    ]
