# Generated by Django 5.0.1 on 2024-01-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_rename_folder_status_shared_folder_folder_statu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shared_folder",
            old_name="folder_statu",
            new_name="folder_status",
        ),
    ]
