# Generated by Django 5.0.1 on 2024-01-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_rename_folder_statu_shared_folder_folder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="datahouse",
            name="chunk_file_id",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
