# Generated by Django 5.0.1 on 2024-01-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_datahouse_chunk_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="datahouse",
            name="totalchunks",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
