# Generated by Django 5.0.1 on 2024-01-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_datahouse_totalchunks"),
    ]

    operations = [
        migrations.RemoveField(model_name="datahouse", name="totalchunks",),
    ]
