# Generated by Django 5.0.1 on 2024-01-18 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_users_old_file_name"),
        ("user", "0018_remove_datahouse_totalchunks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shared_folder",
            name="from_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user_shared_folders",
                to="login.users",
            ),
        ),
        migrations.AlterField(
            model_name="shared_folder",
            name="to_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user_shared_folders",
                to="login.users",
            ),
        ),
    ]
