# Generated by Django 5.0.1 on 2024-01-18 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_users_old_file_name"),
        ("user", "0019_alter_shared_folder_from_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shared_folder",
            name="from_user_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="shared_folder",
            name="to_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="login.users"
            ),
        ),
    ]
